/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TesteRouteImport } from './routes/teste'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSuperintendenteRouteImport } from './routes/_app.superintendente'
import { Route as AppPrevisaoRouteImport } from './routes/_app.previsao'
import { Route as AppPastasRouteImport } from './routes/_app.pastas'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppFinanceiroRouteImport } from './routes/_app.financeiro'
import { Route as AppDiretoriaRouteImport } from './routes/_app.diretoria'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAceleraRouteImport } from './routes/_app.acelera'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as ApiPublicFacebookLeadsRouteImport } from './routes/api.public.facebook-leads'
import { Route as AppFormulariosIdRouteImport } from './routes/_app.formularios.$id'
import { Route as AppAdminUsuariosRouteImport } from './routes/_app.admin.usuarios'
import { Route as AppAdminPainelRouteImport } from './routes/_app.admin.painel'
import { Route as AppAdminLeadsRouteImport } from './routes/_app.admin.leads'
import { Route as AppAceleraIdRouteImport } from './routes/_app.acelera.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const TesteRoute = TesteRouteImport.update({
  id: '/teste',
  path: '/teste',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuperintendenteRoute = AppSuperintendenteRouteImport.update({
  id: '/superintendente',
  path: '/superintendente',
  getParentRoute: () => AppRoute,
} as any)
const AppPrevisaoRoute = AppPrevisaoRouteImport.update({
  id: '/previsao',
  path: '/previsao',
  getParentRoute: () => AppRoute,
} as any)
const AppPastasRoute = AppPastasRouteImport.update({
  id: '/pastas',
  path: '/pastas',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppDiretoriaRoute = AppDiretoriaRouteImport.update({
  id: '/diretoria',
  path: '/diretoria',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAceleraRoute = AppAceleraRouteImport.update({
  id: '/acelera',
  path: '/acelera',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const ApiPublicFacebookLeadsRoute = ApiPublicFacebookLeadsRouteImport.update({
  id: '/api/public/facebook-leads',
  path: '/api/public/facebook-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFormulariosIdRoute = AppFormulariosIdRouteImport.update({
  id: '/formularios/$id',
  path: '/formularios/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsuariosRoute = AppAdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPainelRoute = AppAdminPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLeadsRoute = AppAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAceleraIdRoute = AppAceleraIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAceleraRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teste': typeof TesteRoute
  '/acelera': typeof AppAceleraRouteWithChildren
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/diretoria': typeof AppDiretoriaRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/leads': typeof AppLeadsRoute
  '/pastas': typeof AppPastasRoute
  '/previsao': typeof AppPrevisaoRoute
  '/superintendente': typeof AppSuperintendenteRoute
  '/acelera/$id': typeof AppAceleraIdRoute
  '/admin/leads': typeof AppAdminLeadsRoute
  '/admin/painel': typeof AppAdminPainelRoute
  '/admin/usuarios': typeof AppAdminUsuariosRoute
  '/formularios/$id': typeof AppFormulariosIdRoute
  '/api/public/facebook-leads': typeof ApiPublicFacebookLeadsRoute
  '/admin/': typeof AppAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teste': typeof TesteRoute
  '/acelera': typeof AppAceleraRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/diretoria': typeof AppDiretoriaRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/leads': typeof AppLeadsRoute
  '/pastas': typeof AppPastasRoute
  '/previsao': typeof AppPrevisaoRoute
  '/superintendente': typeof AppSuperintendenteRoute
  '/acelera/$id': typeof AppAceleraIdRoute
  '/admin/leads': typeof AppAdminLeadsRoute
  '/admin/painel': typeof AppAdminPainelRoute
  '/admin/usuarios': typeof AppAdminUsuariosRoute
  '/formularios/$id': typeof AppFormulariosIdRoute
  '/api/public/facebook-leads': typeof ApiPublicFacebookLeadsRoute
  '/admin': typeof AppAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teste': typeof TesteRoute
  '/_app/acelera': typeof AppAceleraRouteWithChildren
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/diretoria': typeof AppDiretoriaRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/pastas': typeof AppPastasRoute
  '/_app/previsao': typeof AppPrevisaoRoute
  '/_app/superintendente': typeof AppSuperintendenteRoute
  '/_app/acelera/$id': typeof AppAceleraIdRoute
  '/_app/admin/leads': typeof AppAdminLeadsRoute
  '/_app/admin/painel': typeof AppAdminPainelRoute
  '/_app/admin/usuarios': typeof AppAdminUsuariosRoute
  '/_app/formularios/$id': typeof AppFormulariosIdRoute
  '/api/public/facebook-leads': typeof ApiPublicFacebookLeadsRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/teste'
    | '/acelera'
    | '/admin'
    | '/dashboard'
    | '/diretoria'
    | '/financeiro'
    | '/leads'
    | '/pastas'
    | '/previsao'
    | '/superintendente'
    | '/acelera/$id'
    | '/admin/leads'
    | '/admin/painel'
    | '/admin/usuarios'
    | '/formularios/$id'
    | '/api/public/facebook-leads'
    | '/admin/'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/teste'
    | '/acelera'
    | '/dashboard'
    | '/diretoria'
    | '/financeiro'
    | '/leads'
    | '/pastas'
    | '/previsao'
    | '/superintendente'
    | '/acelera/$id'
    | '/admin/leads'
    | '/admin/painel'
    | '/admin/usuarios'
    | '/formularios/$id'
    | '/api/public/facebook-leads'
    | '/admin'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/teste'
    | '/_app/acelera'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/diretoria'
    | '/_app/financeiro'
    | '/_app/leads'
    | '/_app/pastas'
    | '/_app/previsao'
    | '/_app/superintendente'
    | '/_app/acelera/$id'
    | '/_app/admin/leads'
    | '/_app/admin/painel'
    | '/_app/admin/usuarios'
    | '/_app/formularios/$id'
    | '/api/public/facebook-leads'
    | '/_app/admin/'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TesteRoute: typeof TesteRoute
  ApiPublicFacebookLeadsRoute: typeof ApiPublicFacebookLeadsRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teste': {
      id: '/teste'
      path: '/teste'
      fullPath: '/teste'
      preLoaderRoute: typeof TesteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/superintendente': {
      id: '/_app/superintendente'
      path: '/superintendente'
      fullPath: '/superintendente'
      preLoaderRoute: typeof AppSuperintendenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/previsao': {
      id: '/_app/previsao'
      path: '/previsao'
      fullPath: '/previsao'
      preLoaderRoute: typeof AppPrevisaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pastas': {
      id: '/_app/pastas'
      path: '/pastas'
      fullPath: '/pastas'
      preLoaderRoute: typeof AppPastasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diretoria': {
      id: '/_app/diretoria'
      path: '/diretoria'
      fullPath: '/diretoria'
      preLoaderRoute: typeof AppDiretoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/acelera': {
      id: '/_app/acelera'
      path: '/acelera'
      fullPath: '/acelera'
      preLoaderRoute: typeof AppAceleraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/api/public/facebook-leads': {
      id: '/api/public/facebook-leads'
      path: '/api/public/facebook-leads'
      fullPath: '/api/public/facebook-leads'
      preLoaderRoute: typeof ApiPublicFacebookLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/formularios/$id': {
      id: '/_app/formularios/$id'
      path: '/formularios/$id'
      fullPath: '/formularios/$id'
      preLoaderRoute: typeof AppFormulariosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/usuarios': {
      id: '/_app/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AppAdminUsuariosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/painel': {
      id: '/_app/admin/painel'
      path: '/painel'
      fullPath: '/admin/painel'
      preLoaderRoute: typeof AppAdminPainelRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/leads': {
      id: '/_app/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AppAdminLeadsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/acelera/$id': {
      id: '/_app/acelera/$id'
      path: '/$id'
      fullPath: '/acelera/$id'
      preLoaderRoute: typeof AppAceleraIdRouteImport
      parentRoute: typeof AppAceleraRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAceleraRouteChildren {
  AppAceleraIdRoute: typeof AppAceleraIdRoute
}

const AppAceleraRouteChildren: AppAceleraRouteChildren = {
  AppAceleraIdRoute: AppAceleraIdRoute,
}

const AppAceleraRouteWithChildren = AppAceleraRoute._addFileChildren(
  AppAceleraRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminLeadsRoute: typeof AppAdminLeadsRoute
  AppAdminPainelRoute: typeof AppAdminPainelRoute
  AppAdminUsuariosRoute: typeof AppAdminUsuariosRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminLeadsRoute: AppAdminLeadsRoute,
  AppAdminPainelRoute: AppAdminPainelRoute,
  AppAdminUsuariosRoute: AppAdminUsuariosRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAceleraRoute: typeof AppAceleraRouteWithChildren
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiretoriaRoute: typeof AppDiretoriaRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppPastasRoute: typeof AppPastasRoute
  AppPrevisaoRoute: typeof AppPrevisaoRoute
  AppSuperintendenteRoute: typeof AppSuperintendenteRoute
  AppFormulariosIdRoute: typeof AppFormulariosIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAceleraRoute: AppAceleraRouteWithChildren,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDiretoriaRoute: AppDiretoriaRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppPastasRoute: AppPastasRoute,
  AppPrevisaoRoute: AppPrevisaoRoute,
  AppSuperintendenteRoute: AppSuperintendenteRoute,
  AppFormulariosIdRoute: AppFormulariosIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TesteRoute: TesteRoute,
  ApiPublicFacebookLeadsRoute: ApiPublicFacebookLeadsRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
